# Generated by Django 6.0.7 on 2026-07-11 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("icono", models.CharField(blank=True, max_length=50)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.IntegerField(default=0)),
                ("color", models.CharField(default="#6c5ce7", max_length=7)),
                ("puntos_base", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("duracion_estimada", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categoria",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.nivel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("juegos_completados", models.IntegerField(default=0)),
                ("puntuacion_total", models.IntegerField(default=0)),
                ("racha_actual", models.IntegerField(default=0)),
                ("racha_maxima", models.IntegerField(default=0)),
                ("tiempo_total", models.IntegerField(default=0)),
                ("ultima_actividad", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("final", "Final"),
                        ],
                        default="formativa",
                        max_length=20,
                    ),
                ),
                ("puntaje_maximo", models.IntegerField(default=100)),
                (
                    "tiempo_limite",
                    models.IntegerField(
                        default=0, help_text="Tiempo en minutos (0 = sin límite)"
                    ),
                ),
                ("intentos_permitidos", models.IntegerField(default=1)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.curso",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecciones",
                        to="core.curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("pregunta", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("opcion", "Opción múltiple"),
                            ("escritura", "Escritura creativa"),
                        ],
                        default="opcion",
                        max_length=20,
                    ),
                ),
                ("opcion1", models.CharField(blank=True, max_length=200)),
                ("opcion2", models.CharField(blank=True, max_length=200)),
                ("opcion3", models.CharField(blank=True, max_length=200)),
                ("opcion4", models.CharField(blank=True, max_length=200)),
                ("respuesta_correcta", models.CharField(max_length=200)),
                ("puntos", models.IntegerField(default=10)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categoria",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.nivel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correcto", models.BooleanField(default=False)),
                ("puntuacion_obtenida", models.IntegerField(default=0)),
                ("tiempo_segundos", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.juego"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("opcion", "Opción Múltiple"),
                            ("verdadero_falso", "Verdadero/Falso"),
                            ("texto", "Respuesta Texto"),
                            ("numerica", "Respuesta Numérica"),
                        ],
                        default="opcion",
                        max_length=20,
                    ),
                ),
                ("pregunta", models.TextField()),
                ("opcion1", models.CharField(blank=True, max_length=200)),
                ("opcion2", models.CharField(blank=True, max_length=200)),
                ("opcion3", models.CharField(blank=True, max_length=200)),
                ("opcion4", models.CharField(blank=True, max_length=200)),
                ("respuesta_correcta", models.TextField()),
                ("puntaje", models.IntegerField(default=10)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="core.evaluacion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_obtenido", models.IntegerField(default=0)),
                ("respuestas", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("completado", "Completado"),
                            ("calificado", "Calificado"),
                        ],
                        default="iniciado",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("tiempo_utilizado", models.IntegerField(default=0)),
                ("intento_numero", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="core.evaluacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_evaluacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "evaluacion", "intento_numero")},
            },
        ),
        migrations.CreateModel(
            name="Progreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("intentos", models.IntegerField(default=0)),
                ("puntuacion", models.IntegerField(default=0)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("ultimo_intento", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.juego"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "juego")},
            },
        ),
        migrations.CreateModel(
            name="ProgresoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_iniciado", "No Iniciado"),
                            ("en_progreso", "En Progreso"),
                            ("completado", "Completado"),
                        ],
                        default="no_iniciado",
                        max_length=20,
                    ),
                ),
                ("lecciones_completadas", models.IntegerField(default=0)),
                ("evaluaciones_completadas", models.IntegerField(default=0)),
                ("puntaje_total", models.IntegerField(default=0)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("ultimo_acceso", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_usuarios",
                        to="core.curso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_cursos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "curso")},
            },
        ),
    ]
